// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type CryptoWallets struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt sql.NullTime
}

type Transactions struct {
	ID        int64
	WalletID  int64
	Amount    int64
	CreatedAt time.Time
}

type Users struct {
	ID         int64
	TelegramID string
}
