// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type CryptoWallet struct {
	ID        int64
	UserID    int64
	Name      string
	Amount    float64
	CreatedAt time.Time
}

type Subscription struct {
	ID             int64
	Type           string
	UserID         int64
	Data           string
	NotifyInterval string
	LastNotifiedAt sql.NullTime
}

type Transaction struct {
	ID        int64
	WalletID  int64
	Amount    float64
	Price     float64
	CreatedAt time.Time
}

type User struct {
	ID         int64
	TelegramID int64
	CreatedAt  time.Time
}
